version: 2.1

defaults: &defaults
  working_directory: ~/oya-project/
  docker:
    - image: registry.hub.docker.com/bilus/oya-circleci:v0.2.0

commands:
  oya_dependencies:
    description: "Install Oya dependencies"
    steps:
      - run: |
          if [ -z "$PGP_KEY" ]
          then
            echo "Set PGP_KEY variable in the project's CircleCI configuration"
            exit 1
          fi
      - run: echo -e "$PGP_KEY" | gpg --import

jobs:
  onPush:
    <<: *defaults
    steps:
      - oya_dependencies
      - checkout
      - setup_remote_docker
      - run: |
          export PATH=~/.oya/bin/:$PATH
          cd docker
          oya run -r -c onPush

  onMerge:
    <<: *defaults
    steps:
      - oya_dependencies
      - checkout
      - setup_remote_docker
      - run: |
          export PATH=~/.oya/bin/:$PATH
          cd docker
          oya run -r -c onMerge
          oya run circleci.onMergeSuccess

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - onPush:
          filters:
            branches:
              ignore:
                - master

      - onMerge:
          filters:
            branches:
              only:
                - master
